### ISSUE TITLE
How to add a `-tw` prefix?

### ISSUE THREAD

**Issue by koffer** [didiercatz/tailwindcss-parcel-boilerplate#2]
Any idea about how to add a prefix: 'tw-',  with the npm run build comand.

**Comment by didier** [comment]
Hey there! Could you elaborate on why you need a prefix?

**Comment by koffer** [comment]
yes. Im using tailwindcss with drupal. Theres actually a theme to use it. In this project they use a prefix, I think to dont conflict with another class (I dont remember a class like that in drupal, anyway...) so they put in a file tailwind.config.js this:

module.exports = {
  prefix: 'tw-',
  important: true,
  theme: {
    extend: {},
    fontFamily: {
     display: ['Gilroy', 'sans-serif'],
     body: ['Graphik', 'sans-serif'],
   },
  },
  variants: {},
  plugins: []
}

So with I compile with npx I get the prefix.

But with the way you use tailwindcss-parcel-boilerplate I saw the improve of create a lighter version of file!

**Comment by didier** [comment]
You should be able to create a tailwind.config.js with that configuration and it should work. Let me know.
