### ISSUE TITLE
Adding extra "/" on builded files path

### ISSUE THREAD

**Issue by Qurus** [didiercatz/tailwindcss-parcel-boilerplate#3]
Adding extra "/" on  files (images and Css) path after building. And 404 file not found error.

**Comment by didier** [comment]
Hey! Thanks for the feedback. Could you elaborate on your issue?

**Comment by Qurus** [comment]
Hello, uploaded a screen shot. If I remove that slashes all fine. 
[https://prnt.sc/rr6eb6](url)
Kind regards.

**Comment by livchits** [comment]
Hi, I like this tool very much :) 
I noticed the same issue. In the final html file the path to the css is 
`<link href="/style.37f46fa6.css" rel="stylesheet">` when it would be like this `<link href="style.37f46fa6.css" rel="stylesheet">`.
I am noobie using tools like Parcel, so I don't know where the problem would be.
